# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: script/bootstrap
  displayName: 'boostrap environment'

- script: script/cibuild
  displayName: 'build theme'

- task: CopyFiles@2
  displayName: 'stage artifact'
  inputs:
    contents: $(Build.SourcesDirectory)/minimalized*.gem
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'publish artifact'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: minimalized
